AllCops:
  Exclude:
    - bin/**/*
    - script/**/*
    - vendor/**/*

ClassAndModuleChildren:
  Enabled: false
ClassLength:
  Enabled: false
CyclomaticComplexity:
  Max: 15
Documentation:
  Enabled: false
DoubleNegation:
  Enabled: false
Encoding:
  Enabled: false
GuardClause:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
NumericLiterals:
  Enabled: false
SignalException:
  Enabled: false
SingleSpaceBeforeFirstArg:
  Enabled: false
Style/FileName:
  Enabled: false
TrailingComma:
  EnforcedStyleForMultiline: comma
