#!/bin/sh
# WARNING: REQUIRES /bin/sh
#
# - must run on /bin/sh on solaris 9
# - must run on /bin/sh on AIX 6.x
# - if you think you are a bash wizard, you probably do not understand
#   this programming language.  do not touch.
# - if you are under 40, get peer review from your elders.
#
PROGNAME=`basename $0`

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

ln -sf /opt/omnibus-toolchain/embedded/bin/git /opt/omnibus-toolchain/bin || error_exit "Cannot link git to /opt/omnibus-toolchain/bin"
ln -sf /opt/omnibus-toolchain/embedded/bin/ruby /opt/omnibus-toolchain/bin || error_exit "Cannot link ruby to /opt/omnibus-toolchain/bin"
ln -sf /opt/omnibus-toolchain/embedded/bin/gtar /opt/omnibus-toolchain/bin || error_exit "Cannot link gtar to /opt/omnibus-toolchain/bin"
ln -sf /opt/omnibus-toolchain/embedded/bin/gtar /opt/omnibus-toolchain/bin/tar || error_exit "Cannot link tar to /opt/omnibus-toolchain/bin"
ln -sf /opt/omnibus-toolchain/embedded/bin/bash /opt/omnibus-toolchain/bin || error_exit "Cannot link bash to /opt/omnibus-toolchain/bin"
ln -sf /opt/omnibus-toolchain/embedded/bin/bundle /opt/omnibus-toolchain/bin || error_exit "Cannot link bundle to /opt/omnibus-toolchain/bin"
ln -sf /opt/omnibus-toolchain/embedded/bin/curl /opt/omnibus-toolchain/bin || error_exit "Cannot link curl to /opt/omnibus-toolchain/bin"
ln -sf /opt/omnibus-toolchain/embedded/bin/fakeroot /opt/omnibus-toolchain/bin || error_exit "Cannot link fakeroot to /opt/omnibus-toolchain/bin"
ln -sf /opt/omnibus-toolchain/embedded/bin/gem /opt/omnibus-toolchain/bin || error_exit "Cannot link gem to /opt/omnibus-toolchain/bin"
ln -sf /opt/omnibus-toolchain/embedded/bin/make /opt/omnibus-toolchain/bin/gmake || error_exit "Cannot link gmake to /opt/omnibus-toolchain/bin"
ln -sf /opt/omnibus-toolchain/embedded/bin/make /opt/omnibus-toolchain/bin/make || error_exit "Cannot link make to /opt/omnibus-toolchain/bin"
ln -sf /opt/omnibus-toolchain/embedded/bin/makedepend /opt/omnibus-toolchain/bin || error_exit "Cannot link makedepend to /opt/omnibus-toolchain/bin"
ln -sf /opt/omnibus-toolchain/embedded/bin/patch /opt/omnibus-toolchain/bin || error_exit "Cannot link patch to /opt/omnibus-toolchain/bin"
ln -sf /opt/omnibus-toolchain/embedded/bin/pkg-config /opt/omnibus-toolchain/bin || error_exit "Cannot link pkg-config to /opt/omnibus-toolchain/bin"
ln -sf /opt/omnibus-toolchain/embedded/bin/rake /opt/omnibus-toolchain/bin || error_exit "Cannot link rake to /opt/omnibus-toolchain/bin"
ln -sf /opt/omnibus-toolchain/embedded/bin/ruby /opt/omnibus-toolchain/bin || error_exit "Cannot link ruby to /opt/omnibus-toolchain/bin"

echo "Thank you for installing the Omnibus Toolchain!"

exit 0
